### PR TITLE
Feature/identity server

### PR DESCRIPTION
**Pull request by DanielTrevorHarding**

### CODE REVIEW

**Comment by gpauer** [comment]
Hi please see workflow failing as JDK 17 not supported with Javalin so we have to stick with 11

**Comment by gpauer** [comment]
Also some dependencies already in parent pom

**Comment by DanielTrevorHarding** [comment]
What I'm working on is the identity server and its an important enough distinction for me to keep the package name the way it is

**Comment by gpauer** [comment]
Cool, its passing now

**Review by gpauer — APPROVED** [review]

**Pull request merged**
